import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NoiseTexture } from "@/registry/magicui/noise-texture";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col relative" suppressHydrationWarning>
        <NoiseTexture
          className={cn(
            "fixed inset-0 z-[-1]",
            "mask-[radial-gradient(100vh_circle_at_center,white,transparent)]"
          )}
        />
        <div className="relative z-10 h-full w-full" suppressHydrationWarning>
          {children}
        </div>
      </body>
    </html>
  );
}
